### ISSUE TITLE
Can you register things to the query API?

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [bbc/nmos-joint-ri#1]
I try to POST to "http://localhost:8082/x-nmos/registration/v1.1/resource/nodes/3b8be755-08ff-452b-b217-c9151eb21193" but get "405 METHOD NOT ALLOWED".

Does the RI allow registration?

-Thomas

**Comment by NEOAdvancedTechnology** [comment]
I figured out to POST to "http://localhost:8082/x-nmos/registration/v1.1/resource".

I got "201 CREATED" back, along with the response header "location:
/x-nmos/registration/v1.1/resource/nodes/3b8be755-08ff-452b-b217-c9151eb21193/"

But if I try to GET "http://localhost:8082/x-nmos/registration/v1.1/resource/nodes/3b8be755-08ff-452b-b217-c9151eb21193/" I receive "404 NOT FOUND", and also my new node does not show up on the Query API at "http://localhost:8082/x-nmos/query/v1.1/nodes/".

Here is the original POST response to http://localhost:8082//x-nmos/registration/v1.1/resource

> date:
> Wed, 04 Apr 2018 22:48:14 GMT
> server:
> Apache/2.4.18 (Ubuntu)
> access-control-allow-origin:
> *
> access-control-allow-methods:
> GET, POST
> access-control-allow-headers:
> CONTENT-TYPE
> access-control-max-age:
> 21600
> cache-control:
> no-cache, must-revalidate, no-store
> content-type:
> application/json
> content-length:
> 1801
> location:
> /x-nmos/registration/v1.1/resource/nodes/3b8be755-08ff-452b-b217-c9151eb21193/

> {
>     "description": "Thomas", 
>     "tags": {}, 
>     "api": {
>         "endpoints": [
>             {
>                 "host": "172.29.80.65", 
>                 "protocol": "http", 
>                 "port": 12345
>             }, 
>             {
>                 "host": "172.29.80.65", 
>                 "protocol": "https", 
>                 "port": 443
>             }
>         ], 
>         "versions": [
>             "v1.0", 
>             "v1.1"
>         ]
>     }, 
>     "hostname": "Thomas", 
>     "label": "Thomas", 
>     "clocks": [
>         {
>             "ref_type": "internal", 
>             "name": "clk0"
>         }, 
>         {
>             "gmid": "08-00-11-ff-fe-21-e1-b0", 
>             "locked": true, 
>             "name": "clk1", 
>             "traceable": true, 
>             "version": "IEEE1588-2008", 
>             "ref_type": "ptp"
>         }
>     ], 
>     "href": "http://172.29.80.65:12345/", 
>     "version": "1441973902:879053935", 
>     "services": [
>         {
>             "href": "http://172.29.80.65:12345/x-manufacturer/pipelinemanager/", 
>             "type": "urn:x-manufacturer:service:pipelinemanager"
>         }, 
>         {
>             "href": "http://172.29.80.65:12345/x-manufacturer/status/", 
>             "type": "urn:x-manufacturer:service:status"
>         }, 
>         {
>             "href": "http://172.29.80.65:12345/x-manufacturer/tally/", 
>             "type": "urn:x-manufacturer:service:tally"
>         }, 
>         {
>             "href": "http://172.29.80.65:12345/x-manufacturer/mdnsbridge/", 
>             "type": "urn:x-manufacturer:service:mdnsbridge"
>         }, 
>         {
>             "href": "http://172.29.80.65:12345/x-manufacturer/storequery/", 
>             "type": "urn:x-manufacturer:service:storequery"
>         }
>     ], 
>     "caps": {}, 
>     "id": "3b8be755-08ff-452b-b217-c9151eb21193"
> }`

**Comment by andrewbonney** [comment]
Hi Thomas,
Are you performing heartbeats once the Node is registered? If not you'll only be able to fetch the Node from the Query API for up to 12 seconds after the registration.

I can't immediately see anything wrong with your request, and I certainly wouldn't expect the API to give you a 201 back unless it had been successfully stored.

**Comment by NEOAdvancedTechnology** [comment]
Ah, yes I do see it briefly on "http://localhost:8082/x-nmos/query/v1.1/nodes/" before the heartbeat timeout, thanks!

I will note that trying to GET from "http://localhost:8082/x-nmos/registration/v1.1/resource/nodes/[ID]" returns a "500: Internal Exception", I believe this should work.

**Comment by andrewbonney** [comment]
Yes that should work. I've added a bug against that repository and will look into it: https://github.com/bbc/nmos-registration/issues/1
