### ISSUE TITLE
Freeze of NMOS Connection Management(http://localhost:8860/)

### ISSUE THREAD

**Issue by soutaroumaejima** [bbc/nmos-joint-ri#2]
I think I have completed all set-up of Vagrant and Virtualbox and VMs staretd successfully.
Host machine can access to http://localhost:8858, 8860 and 8080 by such setup.

However, error message[Internal error] occurred and condition of all functions is freeze when I fill out  and update all parameters of sender and receiver, finally click [Stage File] of Staged Transport File (Receivers Only).

That is situation when functions are freezed.

> <Staged Transport File>

> Staged Transport File:application/sdp

> Data:http://localhost:8080/x-nmos/connection/v1.0/single/senders/e195e014-a19d-431c-b99d-04d09bb47c9d/transportfile/

> sender ID:bbb4207a-90ae-49e8-81d4-b8ccdbd5b049

I want to know what is the cause of error message[Internal error] and freeze.
(Just for your information, host machine is ubuntu 16.04 and activated under proxy server. 
Of course, set up of environment HTTP proxy variables and vagrant plugin for proxy was completed.)

**Comment by andrewbonney** [comment]
Thanks for the report. I can replicate the issue when activating the receiver using a transport file. I don't know immediately what is causing it but we'll look into it.

cc: @simonrankine

**Comment by andrewbonney** [comment]
Just adding some notes here to assist with our debugging:

1) Run 'vagrant up'
2) Load the mock driver interface and add a Sender and Receiver
3) Load the connection management interface and enable the Sender by staging master_enable and then activating
4) Copy the active transport file
5) Stage the transport file, including the file type and Sender ID, with master_enable checked
6) Activate the Receiver. The API fails to respond.

A couple of other unrelated issues I noted in doing this:
- When staging a transport file the UI should pass the master_enable flag through to the API but doesn't appear to
- When opening the Receiver by clicking on its ID, the link to the Active Transport File changes to incorrectly point at the Receiver ID

**Comment by soutaroumaejima** [comment]
I'm sorry for the delay in replying your messagae.

Thank you for sharing infromation! 
I understand that the cause of this error is not clear yet.
Using your information, I will also investigate the cause of it.

Thank you for sincere correspondence.
Please let me question if something also happen.

**Comment by andrewbonney** [comment]
This may be improved (or fixed) by https://github.com/bbc/nmos-device-connection-management-ri/pull/11

**Comment by soutaroumaejima** [comment]
Thank you for your help!

**Comment by andrewbonney** [comment]
Closing as we believe the above will fix the issue, but please re-open if not.
