### ISSUE TITLE
Error at 'vagrant up'

### ISSUE THREAD

**Issue by JahedulAnowar** [bbc/nmos-joint-ri#25]
When `vagrant up` command is used, i get the following error:

`TASK [nmos-service-install : Restart service] **********************************`
`fatal: [node]: FAILED! => {"changed": false, "msg": "Unable to start service python3-nodefacade.service: Job for python3-nodefacade.service failed because the control process exited with error code.\nSee \"systemctl status python3-nodefacade.service\" and \"journalctl -xe\" for details.\n"}`

`RUNNING HANDLER [nmos-service-install : Restart apache service] ****************`

`PLAY RECAP *********************************************************************`
`node                       : ok=58   changed=29   unreachable=0    failed=1    skipped=48   rescued=0    ignored=0  `

`Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

P.S.As i can ssh into the VMs so can this error be ignored?

**Comment by JamesGibo** [comment]
No, as it has failed to start the `python3-nodefacade.service`, which is responsible for running the Node API, so the joint RI will probably be missing the functionality you require. 

Please could you ssh into the VM `vagrant ssh node` and post the output of `systemctl status python3-nodefacade.service`?

**Comment by JahedulAnowar** [comment]
The following is the output:

● python3-nodefacade.service - ips-nodefacade
   Loaded: loaded (/lib/systemd/system/python3-nodefacade.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-06-18 06:50:46 UTC; 42min ago
 Main PID: 903 (python3)
    Tasks: 4 (limit: 1108)
   CGroup: /system.slice/python3-nodefacade.service
           └─903 python3 /usr/bin/nmosnode

Jun 18 07:32:42 node nmosnode[903]: DEBUG:aggregator_proxy:Failed to find registration API
Jun 18 07:32:42 node nmosnode[903]: DEBUG:aggregator_proxy:Entering Discovery Mode
Jun 18 07:32:42 node nmosnode[903]: DEBUG:aggregator_proxy:Backoff timer enabled for 40 seconds
Jun 18 07:33:22 node nmosnode[903]: DEBUG:aggregator_proxy:Flushing cached list of aggregators
Jun 18 07:33:22 node nmosnode[903]: DEBUG:mdnsbridge:IppmDNSBridge priority = 0
Jun 18 07:33:22 node nmosnode[903]: DEBUG:aggregator_proxy:No Registration services found: nmos-registration v1.2 http
Jun 18 07:33:22 node nmosnode[903]: DEBUG:aggregator_proxy:Increasing backoff period
Jun 18 07:33:22 node nmosnode[903]: DEBUG:aggregator_proxy:Failed to find registration API
Jun 18 07:33:22 node nmosnode[903]: DEBUG:aggregator_proxy:Entering Discovery Mode
Jun 18 07:33:22 node nmosnode[903]: DEBUG:aggregator_proxy:Backoff timer enabled for 40 seconds

**Comment by JamesGibo** [comment]
Thanks, I have managed to replicate the error locally and fixed the dependency issue that was causing the issue. 
Let me know if this has not fixed the issue for you. 
Make sure to run `vagrant destroy` before retrying
