### ISSUE TITLE
Registry not working?

### ISSUE THREAD

**Issue by promgamer** [bbc/nmos-joint-ri#3]
I'm trying to use the registry, without success, as shown below. What could be the cause of it?

![image](https://user-images.githubusercontent.com/6740813/44024735-187529d4-9ee6-11e8-8df1-7a0f2de28b21.png)

**Comment by andrewbonney** [comment]
Hi,
I've just tried spinning the vagrant boxes up from scratch and can't replicate this. Does it resolve itself after a few minutes of operation? It's possible that Apache could return this error if you've accessed the URL before the service behind it is fully running.

Otherwise we did resolve a number of issues a couple of weeks back, so if you have an out of date clone of the repository that may be the issue.

**Comment by promgamer** [comment]
I've cloned the repository 2/3 days ago.

I've checked the `/var/log/nmos.log` on the registry machine, but it's empty...

Just to be sure: using this vagrant solution is as easy as git clone + vagrant up, right?

**Comment by andrewbonney** [comment]
It should be, that's certainly all I've had to do when attempting to replicate the issue today.

Could you let me know the exact URL which is producing this error and I might be able to suggest some things to help in debugging?

**Comment by promgamer** [comment]
Ok. Trying again:

```
> vagrant up
Configuring proxy settings...
Bringing machine 'regquery' up with 'virtualbox' provider...
Bringing machine 'node' up with 'virtualbox' provider...
==> regquery: Checking if box 'bento/ubuntu-16.04' is up to date...
==> regquery: Clearing any previously set forwarded ports...
==> regquery: Clearing any previously set network interfaces...
==> regquery: Preparing network interfaces based on configuration...
    regquery: Adapter 1: nat
    regquery: Adapter 2: hostonly
==> regquery: Forwarding ports...
    regquery: 80 (guest) => 8082 (host) (adapter 1)
    regquery: 22 (guest) => 2222 (host) (adapter 1)
==> regquery: Booting VM...
==> regquery: Waiting for machine to boot. This may take a few minutes...
    regquery: SSH address: 127.0.0.1:2222
    regquery: SSH username: vagrant
    regquery: SSH auth method: private key
==> regquery: Machine booted and ready!
==> regquery: Checking for guest additions in VM...
==> regquery: Setting hostname...
==> regquery: Configuring and enabling network interfaces...
==> regquery: Mounting shared folders...
    regquery: /vagrant => /home/mpoeira/nmos-joint-ri/vagrant
    regquery: /vagrant-root => /home/mpoeira/nmos-joint-ri
==> regquery: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> regquery: flag to force provisioning. Provisioners marked to run always will still run.
==> node: Checking if box 'bento/ubuntu-16.04' is up to date...
==> node: Clearing any previously set forwarded ports...
==> node: Fixed port collision for 22 => 2222. Now on port 2200.
==> node: Clearing any previously set network interfaces...
==> node: Preparing network interfaces based on configuration...
    node: Adapter 1: nat
    node: Adapter 2: hostonly
==> node: Forwarding ports...
    node: 80 (guest) => 8080 (host) (adapter 1)
    node: 8858 (guest) => 8858 (host) (adapter 1)
    node: 8860 (guest) => 8860 (host) (adapter 1)
    node: 22 (guest) => 2200 (host) (adapter 1)
==> node: Booting VM...
==> node: Waiting for machine to boot. This may take a few minutes...
    node: SSH address: 127.0.0.1:2200
    node: SSH username: vagrant
    node: SSH auth method: private key
==> node: Machine booted and ready!
==> node: Checking for guest additions in VM...
==> node: Setting hostname...
==> node: Configuring and enabling network interfaces...
==> node: Mounting shared folders...
    node: /vagrant => /home/mpoeira/nmos-joint-ri/vagrant
    node: /vagrant-root => /home/mpoeira/nmos-joint-ri
==> node: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> node: flag to force provisioning. Provisioners marked to run always will still run.
```

So now, if I try to access the node API @ 8080, it works:
![image](https://user-images.githubusercontent.com/6740813/44087247-1e8cd4a8-9fb7-11e8-935c-593c46d065ed.png)

If I try to access the registry @ 8082, it shows this:
![image](https://user-images.githubusercontent.com/6740813/44087269-3abedf9a-9fb7-11e8-8558-2fce983fba19.png)

If I add `/x-nmos` to the URL, it appears the same image as above:
![image](https://user-images.githubusercontent.com/6740813/44087304-51b03b72-9fb7-11e8-8055-ac6c65ecc9b8.png)

But if I then add `/query` to the URL, it appears a 404 - Not Found:
![image](https://user-images.githubusercontent.com/6740813/44087418-ae5ae660-9fb7-11e8-9a4e-3e900443da2b.png)

**Comment by andrewbonney** [comment]
Ok. It sounds like something has gone wrong with the installation of the registry VM, although the Node looks fine. Could you try running a 'vagrant destroy' and then a 'vagrant up' to try creating it from scratch? If the same happens again, could you run 'vagrant ssh regquery' and then the following status commands to check on the services?

```
systemctl status python-registryquery
systemctl status python-registryaggregator
systemctl status ips-reverseproxy-common
systemctl status etcd
```

**Comment by promgamer** [comment]
@andrewbonney just did `vagrant destroy` and `vagrant up` again... And it works!

![image](https://user-images.githubusercontent.com/6740813/44088004-83e3a898-9fb9-11e8-8976-df1feb4a5a80.png)

I guess I messed up with some vagrant stuff (never used before).

Edit: saw your comment while writing this one. sorry for taking your time :disappointed:

**Comment by andrewbonney** [comment]
No problem. We've had a few issues as a result of some internal continuous integration changes anyway so there have definitely been a few faults which may have tripped people up over the past few weeks.

Let me know if you hit any further issues.
